<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration>Debug</Configuration>
    <Platform>AnyCPU</Platform>
    <FileVersion>1.0.01</FileVersion>
    <AssemblyVersion>1.0.0.1</AssemblyVersion>
    <IsPublishable>True</IsPublishable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.AspNetCore">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.36\Microsoft.AspNetCore.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Http">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.36\Microsoft.AspNetCore.Http.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Http.Abstractions">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.36\Microsoft.AspNetCore.Http.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Http.Extensions">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.36\Microsoft.AspNetCore.Http.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Http.Features">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.36\Microsoft.AspNetCore.Http.Features.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Http.Results">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.36\Microsoft.AspNetCore.Http.Results.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Routing">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.36\Microsoft.AspNetCore.Routing.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CSharp">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.36\Microsoft.CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Hosting.Abstractions">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.36\Microsoft.Extensions.Hosting.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Primitives">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.36\Microsoft.Extensions.Primitives.dll</HintPath>
    </Reference>
    <Reference Include="netstandard">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.36\netstandard.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>C:\Users\GMK\Desktop\LWJ\ProfControlV8Update\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="PresentationCore">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.36\PresentationCore.dll</HintPath>
    </Reference>
    <Reference Include="System.Collections">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.36\System.Collections.dll</HintPath>
    </Reference>
    <Reference Include="System.Linq">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.36\System.Linq.dll</HintPath>
    </Reference>
    <Reference Include="System.Linq.Expressions">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.36\System.Linq.Expressions.dll</HintPath>
    </Reference>
    <Reference Include="System.Net">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.36\System.Net.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.36\System.Net.Http.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Requests">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.36\System.Net.Requests.dll</HintPath>
    </Reference>
    <Reference Include="System.Private.CoreLib">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.36\System.Private.CoreLib.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.36\System.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="System.Threading">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.36\System.Threading.dll</HintPath>
    </Reference>
    <Reference Include="WindowsBase">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.36\WindowsBase.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="C:\Users\GMK\Desktop\LWJ\www\ProfControlV8Update\script\floor3pro-test\floor3-pro.cs" />
  </ItemGroup>
</Project>